Repository best-practice-and-impact/CARS, pull requests merged in 2023-01, with the labels that each got.

#27 23 frequency table unit tests
  NAMESPACE
  R/colour_scales.R
  R/data_cleaning.R
  R/derive_vars.R
  R/frequency-tables.R
  R/html.R
  R/ingest.R
  R/plot.R
  man/calculate_multi_table_freqs.Rd
  man/get_2colour_gradients.Rd
  man/get_2colour_scale.Rd
  man/insert_table_toggle.Rd
  man/setup_table_toggle.Rd
  man/summarise_coding_tools.Rd
  tests/testthat/test-calculate_freqs.R
  tests/testthat/test-calculate_multi_table_freqs.R
  tests/testthat/test-derive_advanced_rap_scores.R
  tests/testthat/test-derive_basic_rap_scores.R
  tests/testthat/test-derive_language_status.R
  tests/testthat/test-summarise_ability_change.R
  tests/testthat/test-summarise_adv_score_by_imp.R
  tests/testthat/test-summarise_adv_score_by_understanding.R
  tests/testthat/test-summarise_basic_score_by_imp.R
  tests/testthat/test-summarise_basic_score_by_understanding.R
  tests/testthat/test-summarise_cap_change_by_freq.R
  tests/testthat/test-summarise_ci.R
  tests/testthat/test-summarise_code_freq.R
  tests/testthat/test-summarise_coding_practices.R
  tests/testthat/test-summarise_coding_tools.R
  tests/testthat/test-summarise_dep_man.R
  tests/testthat/test-summarise_doc.R
  tests/testthat/test-summarise_language_status.R
  tests/testthat/test-summarise_languages_by_prof.R
  tests/testthat/test-summarise_line_manage.R
  tests/testthat/test-summarise_operations.R
  tests/testthat/test-summarise_rap_advanced.R
  tests/testthat/test-summarise_rap_basic.R
  tests/testthat/test-summarise_rap_comp.R
  tests/testthat/test-summarise_rap_knowledge.R
  tests/testthat/test-summarise_rap_opinions.R
  tests/testthat/test-summarise_rep_workflow.R
  tests/testthat/test-summarise_where_learned_code.R
Labels: enhancement

#32 Add defra report including agencies
  NAMESPACE
  R/data_cleaning.R
  R/render.R
  main.R
  man/clean_departments.Rd
  tests/testthat/test-clean_departments.R
Labels: enhancement

#31 28 quarto text
  .gitignore
  R/break_q_names.R
  R/colour_scales.R
  R/derive_vars.R
  R/frequency-tables.R
  R/plot.R
  R/render.R
  quarto/main/departments/centre-for-environment-fisheries-and-aquaculture-science.qmd
  quarto/main/departments/department-for-business-energy-and-industrial-strategy-excl-agencies-.qmd
  quarto/main/departments/department-for-digital-culture-media-and-sport.qmd
  quarto/main/departments/department-for-education.qmd
  quarto/main/departments/department-for-environment-food-and-rural-affairs-excl-agencies-.qmd
  quarto/main/departments/department-for-international-trade.qmd
  quarto/main/departments/department-for-levelling-up-housing-and-communities.qmd
  quarto/main/departments/department-for-transport-excl-agencies-.qmd
  quarto/main/departments/department-for-work-and-pensions.qmd
  quarto/main/departments/department-of-health-and-social-care-excl-agencies-.qmd
  quarto/main/departments/forestry-commission.qmd
  quarto/main/departments/government-actuary-s-department.qmd
  quarto/main/departments/hm-revenue-and-customs.qmd
  quarto/main/departments/ministry-of-defence.qmd
  quarto/main/departments/ministry-of-justice-excl-agencies-.qmd
  quarto/main/departments/national-records-of-scotland.qmd
  quarto/main/departments/northern-ireland-statistics-and-research-agency.qmd
  quarto/main/departments/office-for-national-statistics.qmd
  quarto/main/departments/public-health-scotland.qmd
  quarto/main/departments/scottish-government-excl-agencies-.qmd
  quarto/main/departments/uk-health-security-agency.qmd
  quarto/main/departments/welsh-government.qmd
  quarto/main/index.qmd
  quarto/main/professions/data-scientists.qmd
  quarto/main/professions/digital-and-data.qmd
  quarto/main/professions/government-actuarys-department.qmd
  quarto/main/professions/government-economic-service.qmd
  quarto/main/professions/government-geography.qmd
  quarto/main/professions/government-operational-research.qmd
  quarto/main/professions/government-social-research.qmd
  quarto/main/professions/government-statician-group.qmd
  quarto/main/summary.qmd
  quarto/templates/summary.qmd
  tests/testthat/test-derive_language_status.R
  tests/testthat/test-summarise_coding_tools.R
  tests/testthat/test-summarise_language_status.R
Labels: enhancement

#36 Removed neither from language status
  R/frequency-tables.R
  quarto/main/summary.qmd
  quarto/templates/summary.qmd
  tests/testthat/test-summarise_coding_practices.R
  tests/testthat/test-summarise_language_status.R
Labels: enhancement

#37 Populated department and profession pages with plots
  quarto/main/departments.qmd
  quarto/main/summary.qmd
  quarto/templates/summary.qmd
Labels: enhancement

#39 Updated basic_RAP_score plot colour and mentioned where variables hav…
  R/frequency-tables.R
  quarto/main/summary.qmd
  quarto/templates/summary.qmd
  tests/testthat/test-summarise_where_learned_code.R
Labels: bug

#40 First draft changes
  DESCRIPTION
  LICENSE.md
  R/plot.R
  README.md
  quarto/main/index.qmd
  quarto/main/summary.qmd
  quarto/templates/summary.qmd
Labels: documentation
